/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.caucho.vfs.*;
import com.caucho.server.webapp.*;

public class _index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
/**
 * See if the resin-doc webapp is installed
 */
boolean hasResinDoc = false;
boolean hasOrientation = false;

ServletContext docApp = application.getContext("/resin-doc");  

if (docApp != null) {
  String rp = docApp.getRealPath("index.xtp");

  if (rp != null && (new java.io.File(rp)).exists())
    hasResinDoc = true;

  if (hasResinDoc) {
    rp = docApp.getRealPath("orientation.xtp");
    if (rp != null && (new java.io.File(rp)).exists())
      hasOrientation = true;
  }
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
       if (hasResinDoc) { 
      out.write(_jsp_string2, 0, _jsp_string2.length);
       if (hasOrientation) { 
      out.write(_jsp_string3, 0, _jsp_string3.length);
       } 
      out.write(_jsp_string4, 0, _jsp_string4.length);
       } else { 
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( request.getScheme() ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( request.getServerName() ));
      out.write(':');
      out.print(( request.getServerPort() ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
       }  
      out.write(_jsp_string8, 0, _jsp_string8.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), 7924897343049059564L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string8;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string6;
  static {
    _jsp_string8 = "\n</body>\n\n</html>\n".toCharArray();
    _jsp_string4 = "\n\n<p>\nDocumentation is available <a href=\"/resin-doc\">here</a>.\n\n<p>\nAdministration is available <a href=\"/resin-admin\">here</a>.\n\n".toCharArray();
    _jsp_string5 = "\n<p>\nThe Resin documentation is normally found with the url  <i>\n".toCharArray();
    _jsp_string0 = "\n\n\n\n".toCharArray();
    _jsp_string7 = "/resin-doc</i>, but it does not appear to be installed at that location.\n".toCharArray();
    _jsp_string3 = "\n<p>\nNew users can start <a href=\"/resin-doc/orientation.xtp?xtpflag=default-homepage\">here</a>.\n".toCharArray();
    _jsp_string2 = "\n\n".toCharArray();
    _jsp_string1 = "\n\n<html>\n<head><title>Resin&#174; Default Home Page</title></head>\n\n<body>\n<h1 style=\"background: #ccddff\">Resin&#174; Default Home Page</h1>\n\nThis is the default page for the Resin web server.\n\n".toCharArray();
    _jsp_string6 = "://".toCharArray();
  }
}
